### ISSUE TITLE
Is this plugin updated on pub.dev ? Can I use it in production apps.

### ISSUE THREAD

**Issue by muzammil-git** [cybex-dev/twilio_voice#148]
Are updates being reflected on https://pub.dev/packages/twilio_voice ? Its written 2 years ago.

![image](https://github.com/diegogarciar/twilio_voice/assets/54685589/6de88ff5-7a4b-4494-90ce-2e8eea1a86ea)

**Comment by cybex-dev** [comment]
@muzammil-git 

Thanks for getting in touch, 0.0.9 is stable, however there has since been a number of additions, bug fixes, etc. I'm in the processing of making feature additions and will be release a 1.0.0 version in the next 1-2 weeks.

Feel free to use `master` for now (testing) while I finish with updates.

**Comment by muzammil-git** [comment]
Thankyou for the quick response, it helps. Have a great weekend !
