### ISSUE TITLE
How to terminate Native  Call Ui  When Create Make Call

### ISSUE THREAD

**Issue by lavishmanghnani2** [cybex-dev/twilio_voice#226]
when i  create a make call using this :-
                                                                 await TwilioVoice.instance.call.place(
                                                                 to: "+91xxxxxxxx", from: "+91xxxxxxxxxx",);
                                                                 
                                  it  show native ui of calling . i want to  navigate own create screen , how i do please tell

**Comment by cybex-dev** [comment]
Good day @lavishmanghnani2,

In version 0.0.9, this feature was available in Android. The rationale behind using the native system calling UIs is due to the limitations of iOS. 

iOS requires any app to utilize their CallKit for any telephonic features, thus integrating into the native "callkit" of Android platforms to ensure no custom dependency and irregularity between platforms.

Feel free to open a feature request, to see the interest in custom Android call screens. With sufficient demand, I'd reintroduce this feature.
