### ISSUE TITLE
Accessing call duration after answer

### ISSUE THREAD

**Issue by Yahllil** [cybex-dev/twilio_voice#65]
How can we access the outgoing call duration after the other side has answered the call?
The callEventListener stream does not yield when the other side answered so we can't start a timer in our side.

**Comment by diegogarciar** [comment]
Hello, first of all I don't think there's a call duration variable, I think you must count the time yourself after a specific event occurs.

I have tried to implement a counter that starts when the user answers the call many times and it seems not possible, even in native. The reason is that we get a `connected` message when it starts ringing and not when the other user answers the call. 

However I think is technically possible is you perform the call with [answerOnBridge](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) but it involves [more complexity](https://github.com/twilio/voice-quickstart-ios/blob/2b6b96ce26a88bd3b9e290a3570207d6e6e3c5ff/SwiftVoiceQuickstart/ViewController.swift#L55) as I think you have to handle the ringing of the call so I've never tried that. 

The alternative is to start the a counter when you get the `connected` message.

**Comment by cybex-dev** [comment]
My implementation uses Firebase as a backend and listening for both to report a connected state, something like Firebase's realtime database.

**Comment by diegogarciar** [comment]
Closing this for now as it is not an issue, but feel free to continue the conversation
