### ISSUE TITLE
Custom UI for incoming call

### ISSUE THREAD

**Issue by Yahllil** [cybex-dev/twilio_voice#67]
How can we change the UI of the incoming call in Android and iOS (both in foreground and background)?

Thank you

**Comment by cybex-dev** [comment]
**iOS**
All Apple/iOS devices uses CallKit for incoming/(native) outgoing calls. This is a standardized library for iOS to make all apps accepting calling (VoIP or otherwise) use the same look. See this for more information:
> CallKit displays the same interfaces as the Phone app, giving your app a more native look and feel. CallKit also responds appropriately to system-level behaviors such as Do Not Disturb.
[see docs for more information](https://developer.apple.com/documentation/callkit)

- [Changing (screen) & answering calls with CallKit](https://stackoverflow.com/questions/69650283/open-ios-flutter-app-directly-after-answering-voip-call-from-locked-ios-device)

**Android**
Android provides a degree of customizability. You can edit the Android device code [here](https://github.com/diegogarciar/twilio_voice/tree/master/android) to display which ever notification/screen you want on the device. 

To edit:
1. First, Run the example, review the Android call screen and see what is being shown
2. (optional) clone/fork (this) library
3. Edit android app to your liking
4. Integrate library into your app by editing your project's `pubspec.yaml`
```yaml
twilio_voice: 
    path: ./relative/path/to/twilio_voice
```

**Please note:**
Since Flutter is cross-platform, ideally you would like to keep the UX consistent across platforms, thus having a different looking Android/iOS UI may not bode well for the UX - try to keep these similar.

**Comment by diegogarciar** [comment]
Closing this as its not an issue with the package
